### ISSUE TITLE
Redirect to Homepage after successful SignIn/SignUp

### ISSUE THREAD

**Issue by Nisha1205092** [Nisha1205092/crown-clothing#4]
Instead of staying on the Authentication page, redirect to Home page after successful SignIn/SignUp.

**Comment by alefDev-prog** [comment]
Hi, I think that I could fix this tomorrow

**Comment by Nisha1205092** [comment]
Hi, I'd love that! Let me know if you need anything!

**Comment by alefDev-prog** [comment]
Please let me know which branch I should use

**Comment by Nisha1205092** [comment]
Kindly use the master branch, fork it and make necessary changes. Sorry for my readme not having specific instructions about how to run it locally on a machine. Let me know if you need that information.

**Comment by Nisha1205092** [comment]
Hello,
Thank you for your contribution. As you might guess, I'm quite a noob. I
wanted to know about something. How much did you have to set up for the
project to work on your machine? Like there is setup for Firebase and
Stripe. Is there any easy way to do it?

**Comment by Nisha1205092** [comment]
Oh, nice, thanks again!!

**Comment by Nisha1205092** [comment]
By the way, if you are interested, we can connect via Discord.

**Comment by alefDev-prog** [comment]
Thanks, but I am not a discord user. If I find time, I will be glad to contribute to your repository again!
